name: Create envfile
on: [ push ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: LizAinslie/VueBuildToBranchAction@1.0.2
      with:
        username: 'cznethub'
        reponame: 'cznet-discovery'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        VUE_APP_REALM_API_KEY: ${{ secrets.VUE_APP_REALM_API_KEY }}
        VUE_APP_REALM_APP_ID: ${{ secrets.VUE_APP_REALM_APP_ID }}

